CREATE TABLE etab (
"siren" INTEGER ,
"siret" INTEGER ,
"denomination" VARCHAR(255),
"date_creation" DATE,
"dt_crea_etab" DATE,
"effectifs" VARCHAR(2),
"effectifs_etab" VARCHAR(2),
"effectifs_annee" INTEGER ,
"ess" BOOLEAN,
"ent_type" VARCHAR(5),
"ent_type_annee" INTEGER ,
"forju" INTEGER ,
"etab_siege" BOOLEAN,
"naf" VARCHAR(7),
"naf_version" VARCHAR(10),
"naf_etab" VARCHAR(7),
"naf_version_etab" VARCHAR(10),
"adr_code_commune" VARCHAR(10),
"adr_code_etranger" VARCHAR(10),
"adr_code_postal" INTEGER ,
"adr_commune" VARCHAR(255),
"adr_lib_voie" VARCHAR(255),
"adr_num_voie" VARCHAR(5),
"adr_type_voie" VARCHAR(255)
);
