name: pre-commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -U pip setuptools wheel && pip install -r requirements/dev.txt && pre-commit install
    - name: Analysing the code with pre-commit
      run: |
        pre-commit run --all-files
    - name: Unit tests
      run: |
        pytest
